# CalibBoard配置文件
calib_board_node:
  ros__parameters:
    # 点云文件路径
    data_path: "/home/pix/code/calibration_ws/src/calibBoard/data"
    
    # 模板图像文件路径
    template_image_path: "/home/pix/code/calibration_ws/src/calibBoard/data/template.png"

    # 缓存文件路径
    cache_directory: "/home/pix/code/calibration_ws/src/calibBoard/cache"

    # 外参文件路径
    parameters_path: "/home/pix/code/calibration_ws/src/calibBoard/config"

    # 外参文件路径（初始值）
    parameters_path_gt: "/home/pix/code/calibration_ws/src/calibBoard/config/sensor_kit_calibration_gt.yaml"

    # 发布频率 (Hz)
    publish_frequency: 1.0
    
    # 点云话题名称
    pointcloud_topic: "pointcloud_board"
    pointcloud_target_topic: "pointcloud_target"

    # BBox话题名称
    bbox_topic: "bbox_array"
    
    # 坐标系名称
    frame_id: "base_link"

     # 待标定相机ID列表
    camera_list: [0, 1, 2, 3, 4, 5, 6]
    camera_name_list: ["camera_front_4k", "camera_front", "camera_rear", "camera_front_left", "camera_front_right", "camera_rear_left", "camera_rear_right"]
    calib_camera_list: [6]

    # 是否输出用于yolo训练的图像素材
    export_yolo_data: 0

    # 算法参数
    algorithm_params:
      # 算法选择
      algorithm: "ceres_restrain"  # "ceres" / "ceres_restrain" / "epnp"

      # 点云过滤范围
      min_point: [-10.0, -100.0, -40.0, 1.0]  # [x, y, z, w]
      max_point: [25.0, 100.0, 40.0, 1.0]   # [x, y, z, w]
      
      # 尺寸限制参数
      min_size: 0.85     # 最小尺寸（米）
      max_size: 1.5     # 最大尺寸（米）
       
       # 支架过滤宽度
      bracket_width: 0.15  # 支架宽度（米）
      
      # 长宽比阈值
      aspect_ratio_threshold: 1.0  # 长宽比阈值

    # ArUco标记参数
    aruco_params:
      marker_length: 0.51  # 单个Aruco标记的边长（米）
      marker_scale: 2.2     # 外围框放大比例
      marker_shift: 0.15     # 外围框平移比例
      marker_num: 4
      marker_order: [5, 1, 4, 2]  # ArUco标记顺序
